### ISSUE TITLE
Rule MD010 does not exclude code blocks.

### ISSUE THREAD

**Issue by jackdewinter** [jackdewinter/pymarkdown#737]
There is configuration for handling these, but nothing to act on.

**Comment by officel** [comment]
I hit this problem today. Do you have a plan to fix it?

I record the commands and their execution results in a markdown.
Today I am experimenting with options for the dig command and I don't want to replace the recording of the results with spaces.

It would be nice if `code_blocks: false` would work.

Thank you.

**Comment by jackdewinter** [comment]
Its on my list of things to fix prior to the next release.  Probably within the next week or so.

**Comment by jackdewinter** [comment]
Have the detection logic in for fenced code blocks, not indented code block.  That will come next.
Also, current implementation will take:
````
1.  xx
    ```code
\thas\ttab
    ```
````
and allow both tabs, not just the tab in the code block.  That fix is more involved, and looking into it for a future fix.

**Comment by jackdewinter** [comment]
This should be addressed with the v0.9.13 release. Please let me know if those changes work for you!

**Comment by officel** [comment]
```bash
[INFO] Installing environment for https://github.com/jackdewinter/pymarkdown.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
PyMarkdown...............................................................Failed
- hook id: pymarkdown
- exit code: 1

Traceback (most recent call last):
  File "/home/raki/.cache/pre-commit/repohf_wi3y7/py_env-python3/bin/pymarkdown", line 5, in <module>
    from pymarkdown.__main__ import main
  File "/home/raki/.cache/pre-commit/repohf_wi3y7/py_env-python3/lib/python3.11/site-packages/pymarkdown/__init__.py", line 5, in <module>
    from pymarkdown.main import PyMarkdownLint  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raki/.cache/pre-commit/repohf_wi3y7/py_env-python3/lib/python3.11/site-packages/pymarkdown/main.py", line 22, in <module>
    from pymarkdown.extension_manager.extension_manager import ExtensionManager
  File "/home/raki/.cache/pre-commit/repohf_wi3y7/py_env-python3/lib/python3.11/site-packages/pymarkdown/extension_manager/extension_manager.py", line 20, in <module>
    from pymarkdown.extensions.front_matter_extension import FrontMatterExtension
  File "/home/raki/.cache/pre-commit/repohf_wi3y7/py_env-python3/lib/python3.11/site-packages/pymarkdown/extensions/front_matter_extension.py", line 15, in <module>
    from pymarkdown.extensions.front_matter_markdown_token import FrontMatterMarkdownToken
  File "/home/raki/.cache/pre-commit/repohf_wi3y7/py_env-python3/lib/python3.11/site-packages/pymarkdown/extensions/front_matter_markdown_token.py", line 7, in <module>
    from pymarkdown.general.parser_helper import ParserHelper
ModuleNotFoundError: No module named 'pymarkdown.general'
```

I'm sorry. I am not very good at python (nor English).
I use pre-commit, but when I upgraded, I got an error.
I'll check back later.

**Comment by officel** [comment]
```
$ git diff --cached
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 7165851..53ee7ed 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -23,7 +23,7 @@ repos:
       - id: end-of-file-fixer
       - id: trailing-whitespace
   - repo: https://github.com/jackdewinter/pymarkdown
-    rev: v0.9.12
+    rev: v0.9.13
     hooks:
       - id: pymarkdown
         exclude: |
diff --git a/.pymarkdown.json b/.pymarkdown.json
index 462caff..8057cc5 100644
--- a/.pymarkdown.json
+++ b/.pymarkdown.json
@@ -1,7 +1,7 @@
 {
     "plugins" : {
         "no-hard-tabs": {
-            "enabled": false,
+            "enabled": true,
             "code_blocks": false
         },
         "no-multiple-blanks": {
diff --git a/notes/dig.md b/notes/dig.md
index 67a7968..706e609 100644
--- a/notes/dig.md
+++ b/notes/dig.md
@@ -7,7 +7,7 @@

 ```bash
 $ dig @8.8.8.8 SOA +noall +ans oisix.com
-oisix.com.             300     IN      SOA     ns-172.awsdns-21.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
+oisix.com.    300      IN      SOA     ns-172.awsdns-21.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

 $ dig @8.8.8.8 MX +noall +ans oisix.com
 oisix.com.             300     IN      MX      10 mail01.oisix.com.
```

I don't know if this will help, but I'll post the changes.

**Comment by jackdewinter** [comment]
Try.. https://github.com/jackdewinter/pymarkdown/releases/tag/v0.9.13.3

the release verification pipeline did not trigger as expected... and forgot to do a manual check.

**Comment by officel** [comment]
Thank you!
I have tried but I still can't seem to ignore the inside of the code block.

```bash
$ git diff --cached
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 7165851..58faaec 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -23,7 +23,7 @@ repos:
       - id: end-of-file-fixer
       - id: trailing-whitespace
   - repo: https://github.com/jackdewinter/pymarkdown
-    rev: v0.9.12
+    rev: v0.9.13.3
     hooks:
       - id: pymarkdown
         exclude: |
diff --git a/.pymarkdown.json b/.pymarkdown.json
index 462caff..8057cc5 100644
--- a/.pymarkdown.json
+++ b/.pymarkdown.json
@@ -1,7 +1,7 @@
 {
     "plugins" : {
         "no-hard-tabs": {
-            "enabled": false,
+            "enabled": true,
             "code_blocks": false
         },
         "no-multiple-blanks": {
diff --git a/notes/dig.md b/notes/dig.md
index 67a7968..8184889 100644
--- a/notes/dig.md
+++ b/notes/dig.md
@@ -6,8 +6,9 @@
 # oisix.com

 ```bash
+       # test tab
 $ dig @8.8.8.8 SOA +noall +ans oisix.com
-oisix.com.             300     IN      SOA     ns-172.awsdns-21.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
+oisix.com.    300      IN      SOA     ns-172.awsdns-21.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

 $ dig @8.8.8.8 MX +noall +ans oisix.com
 oisix.com.             300     IN      MX      10 mail01.oisix.com.
```

run

```bash
$ pre-commit run pymarkdown
PyMarkdown...............................................................Failed
- hook id: pymarkdown
- exit code: 1

notes/dig.md:9:1: MD010: Hard tabs [Column: 1] (no-hard-tabs)
notes/dig.md:11:18: MD010: Hard tabs [Column: 18] (no-hard-tabs)
notes/dig.md:11:23: MD010: Hard tabs [Column: 23] (no-hard-tabs)
notes/dig.md:11:28: MD010: Hard tabs [Column: 28] (no-hard-tabs)
notes/dig.md:14:11: MD010: Hard tabs [Column: 11] (no-hard-tabs)
<omit>
```

**Comment by jackdewinter** [comment]
are you trying to use `.pymarkdown` but adding `.json` to the end of it?  the default JSON configuration is `.pymarkdown` in the current directory.   if you want to use `.pymarkdown.json`, try `--config .pymarkdown.json` on the command line.

thoughts?

**Comment by officel** [comment]
yes, my  `.pre-commit-config.yaml` is

```bash
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.13.3
    hooks:
      - id: pymarkdown
        exclude: |
          (?x)^(
            aws/panel.md|
            jq/[\d|\w|_]+\/(.*?)\.md|
            path/to/file3.py
          )$
        args:
          - --config=.pymarkdown.json
          - scan
```

and

```bash
cat .pymarkdown.json
{
    "plugins" : {
        "no-hard-tabs": {
            "enabled": true,
            "code_blocks": false
        },
        "no-multiple-blanks": {
            "maximum": 2
        },
        "blanks-around-headers": {
            "lines_above": 1,
            "lines_below": 1
        },
        "line-length": {
            "enabled": true,
            "line_length": 160,
            "heading_line_length": 160,
            "code_blocks": false
        },
        "no-inline-html": {
            "enabled": false
        },
        "single-title": {
            "enabled": false
        },
        "ul-style": {
            "enabled": false
        }
    },
    "extensions" : {
        "front-matter": {
            "enabled": true
        }
    }
}
```

Works fine except for no-hard-tabs

**Comment by jackdewinter** [comment]
Check now against `39770f261aaae32f56409129a76801fe7edd44e9`... it should fix the problem.  The verbiage for the documentation says "check" and the internal variable was "allow".  Fixed to reflect this properly.

**Comment by officel** [comment]
@jackdewinter 

I was able to do it! It seems to be ok.
Great job. Thank you!

```bash
$ git diff --cached
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index c377226..4f86012 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -23,7 +23,7 @@ repos:
       - id: end-of-file-fixer
       - id: trailing-whitespace
   - repo: https://github.com/jackdewinter/pymarkdown
-    rev: v0.9.13.3
+    rev: 39770f261aaae32f56409129a76801fe7edd44e9
     hooks:
       - id: pymarkdown
         exclude: |
diff --git a/.pymarkdown.json b/.pymarkdown.json
index 462caff..8057cc5 100644
--- a/.pymarkdown.json
+++ b/.pymarkdown.json
@@ -1,7 +1,7 @@
 {
     "plugins" : {
         "no-hard-tabs": {
-            "enabled": false,
+            "enabled": true,
             "code_blocks": false
         },
         "no-multiple-blanks": {
diff --git a/notes/dig.md b/notes/dig.md
index 67a7968..706e609 100644
--- a/notes/dig.md
+++ b/notes/dig.md
@@ -7,7 +7,7 @@

 ```bash
 $ dig @8.8.8.8 SOA +noall +ans oisix.com
-oisix.com.             300     IN      SOA     ns-172.awsdns-21.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
+oisix.com.    300      IN      SOA     ns-172.awsdns-21.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

 $ dig @8.8.8.8 MX +noall +ans oisix.com
 oisix.com.             300     IN      MX      10 mail01.oisix.com.
$ pre-commit run pymarkdown
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/raki/.cache/pre-commit/patch1694265465-477971.
PyMarkdown...............................................................Passed
[INFO] Restored changes from /home/raki/.cache/pre-commit/patch1694265465-477971.
```

**Comment by jackdewinter** [comment]
closing after verification
